### _default

# baseURL: "https://14jcjc.github.io/tech-blog/"
# baseURL: "http://localhost:1313/tech-blog/" # é–‹ç™ºç’°å¢ƒç”¨ã® URL
theme: hugo-theme-stack

copyright: katsu
author: katsu
# description: 

# Include drafts when building.
# buildDrafts: false
buildDrafts: true

languageCode: ja
# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: ja

title: katsu DS Lab
# title: katsuãƒ–ãƒ­ã‚°
# title: Katsu Data Science Lab
# title: katsu ãƒ‡ãƒ¼ã‚¿ã‚µã‚¤ã‚¨ãƒ³ã‚¹ãƒ©ãƒœ
# title: katsu ãƒ‡ãƒ¼ã‚¿ã‚µã‚¤ã‚¨ãƒ³ã‚¹ãƒ»ãƒ©ãƒœ
# title: katsu DS ãƒ©ãƒœ
# title: katsu DSå®Ÿè·µãƒ©ãƒœ

# languages:
#     ja:
#         languageName: Japanese
#         contentDir: "content/ja"
#         # title: Katsu Data Science Lab
#         weight: 1
#         params:
#             sidebar:
#                 subtitle: "R ã¨ SQL ã§å­¦ã¶ã€ãƒ‡ãƒ¼ã‚¿æ´»ç”¨ã®å®Ÿè·µã‚¹ã‚­ãƒ«"
#     en:
#         languageName: English
#         # title: Example Site
#         weight: 2
#         params:
#             sidebar:
#                 subtitle: Real-World Data Mastery with R & SQL
#     zh-cn:
#         languageName: ä¸­æ–‡
#         # title: æ¼”ç¤ºç«™ç‚¹
#         weight: 3
#         params:
#             sidebar:
#                 subtitle: æ¼”ç¤ºè¯´æ˜
#     ar:
#         languageName: Ø¹Ø±Ø¨ÙŠ
#         languagedirection: rtl
#         title: Ù…ÙˆÙ‚Ø¹ ØªØ¬Ø±ÙŠØ¨ÙŠ
#         weight: 4
#         params:
#             sidebar:
#                 subtitle: ÙˆØµÙ ØªØ¬Ø±ÙŠØ¨ÙŠ

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true
isCJKLanguage: true # (?) å†…å®¹è¨€èªãŒæ—¥ä¸­éŸ“ç³»ã®ã¨ãã¯ true ã«è¨­å®šã—ã¾ã™.

enableRobotsTXT: true # robots.txt ã®ç”Ÿæˆã‚’æœ‰åŠ¹ã«ã™ã‚‹
enableInlineShortcodes: true # Markdownå†…ã§ã‚¤ãƒ³ãƒ©ã‚¤ãƒ³ã‚·ãƒ§ãƒ¼ãƒˆã‚³ãƒ¼ãƒ‰ã‚’æœ‰åŠ¹åŒ–ã™ã‚‹

# ã‚·ãƒ³ãƒœãƒªãƒƒã‚¯ãƒªãƒ³ã‚¯ã‚’æœ‰åŠ¹åŒ–ã™ã‚‹
enableSymlinksIfOwnerMatch: true

buildFuture: false # Include content with a future publication date.
buildExpired: false # Include content already expired.
enableEmoji: true

# capitalizeListTitles: true
capitalizeListTitles: false

titleCaseStyle: ap # ap, chicago, go, firstupper, or none.
# summaryLength: 50

# å„ãƒšãƒ¼ã‚¸ã® .GitInfo ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã‚’æœ‰åŠ¹ã«ã—ã¾ã™ (Hugo ã‚µã‚¤ãƒˆãŒ Gitã§ãƒãƒ¼ã‚¸ãƒ§ãƒ³ç®¡ç†ã•ã‚Œã¦ã„ã‚‹å ´åˆï¼‰.
# ã“ã‚Œã«ã‚ˆã‚Šã€å„ãƒšãƒ¼ã‚¸ã® Lastmod ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿ãŒ, ãã®ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ãƒ•ã‚¡ã‚¤ãƒ«ã®æœ€å¾Œã® git ã‚³ãƒŸãƒƒãƒˆæ—¥æ™‚ã§æ›´æ–°ã•ã‚Œã¾ã™.
# ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã¯ false ã§ã™ã€‚
enableGitInfo: true

timeout: 90s # Timeout for generating page contents, specified as a duration or in seconds.

# sitemap: 
  # changefreq = "monthly"
  # priority = 0.5

# minify:
#   disableXML: true
#   minifyOutput: true

pagination:
    pagerSize: 10

# permalinks:
#     page: /:slug/
#     post: /p/:slug/
#     test: /test/:slug/

params:
    # mainSections:
    #   - "ds-drills"
    #   - test
    #   - post

    ShowShareButtons: true
    # disableShare: false

    # ã‚¹ãƒãƒ›ç”»é¢ã§ã®ç›®æ¬¡
    UseHugoToc: true
    ShowToc: true
    TocOpen: true
    tableOfContents:
      ordered: false
      startLevel: 2
      endLevel: 4

    # To customize which share buttons to be enabled on page: 
    # ShareButtons: ["x", "linkedin", "facebook", "telegram"]

    # Front Matter field used to get the featured image of a page: 
    featuredImageField: image

    rssFullContent: true # Output page's full content in RSS.

    favicon: "favicon.png"
    
    # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

    footer:
        since: 2025
        # HTML is supported -> markdownify ã«æ”¹ä¿®: 
        # [Privacy Policy]({{< ref "/privacy" >}})
        customText: |
          {{< href-target-blank url="/privacy" text="Privacy Policy" class="link-2" target="_self" >}}
    
    dateFormat:
        published: "2006-01-02"
        lastUpdated: "2006-01-02 15:04 JST"

    sidebar:
        compact: false
        # compact: true
        # emoji: "ğŸ§‘â€ğŸ’»"
        # subtitle: "ç¾å ´ã§å½¹ç«‹ã¤ãƒ‡ãƒ¼ã‚¿ã®ä¸–ç•Œ : Rã¨SQLã§å­¦ã¶å®Ÿè·µã‚¹ã‚­ãƒ«"
        # subtitle: "ç¾å ´ã§å½¹ç«‹ã¤ãƒ‡ãƒ¼ã‚¿ã®ä¸–ç•ŒğŸŒ<br>R ã¨ SQL ã§å­¦ã¶å®Ÿè·µã‚¹ã‚­ãƒ«"
        # subtitle: "R ã¨ SQL ã§å­¦ã¶ã€ãƒ‡ãƒ¼ã‚¿æ´»ç”¨ã®å®Ÿè·µã‚¹ã‚­ãƒ«"
        # subtitle: Real-World Data Mastery with R & SQL
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        toc: true # ãŠãã‚‰ãç„¡åŠ¹ãªãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿ (frontmatterã§æŒ‡å®šå¯)
        headingAnchor: true # è¦‹å‡ºã—ã®ã‚¢ãƒ³ã‚«ãƒ¼
        # headingAnchor: false # è¦‹å‡ºã—ã®ã‚¢ãƒ³ã‚«ãƒ¼
        math: true
        readingTime: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0
    widgets:
        homepage:
            - type: search
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 20
            - type: archives
              params:
                  limit: 2
        page:
            - type: toc
            - type: tag-cloud
              params:
                  limit: 30
            # - type: sharebutton
            - type: share-icons
              params:
                icon: true
                # shareButtons: ["x", "linkedin", "facebook", "telegram"]
    
    opengraph:
    # Open Graph ãƒ—ãƒ­ãƒˆã‚³ãƒ«ã«ã‚ˆã‚Š, ä»»æ„ã®Webãƒšãƒ¼ã‚¸ã‚’ã‚½ãƒ¼ã‚·ãƒ£ãƒ«ã‚°ãƒ©ãƒ•å†…ã®ãƒªãƒƒãƒã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã«ã™ã‚‹ã“ã¨ãŒã§ãã‚‹
        twitter:
            # Your Twitter username
            site: katsu_ds_lab

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph: 
            # Open Graph ã¨ Twitter ã®ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆç”»åƒã‚’æœ‰åŠ¹ã«ã™ã‚‹: 
            enabled: true
            # If true, the image is a local file, and must be placed under assets folder. Otherwise, it is a remote URL.
            local: true
            # For example, if src is set to img/default.jpg, the image file must be placed under assets/img/default.jpg.
            src: img/cover-100k.png

    colorScheme:
        # Display toggle
        toggle: true
        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true
    
    comments:
        # enabled: true
        enabled: false
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        beaudar:
            repo:
            issueTerm: pathname
            label:
            theme:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/component.html
        waline:
            serverURL:
            lang:
            pageview:
            emoji:
                - https://unpkg.com/@waline/emojis@1.0.1/weibo
            requiredMeta:
                - name
                - email
                - url
            locale:
                admin: Admin
                placeholder:

        twikoo:
            envId:
            region:
            path:
            lang:

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:
            proxy:

        cusdis:
            host:
            id:

# ã‚»ã‚¯ã‚·ãƒ§ãƒ³ã®ãƒ¡ãƒ‹ãƒ¥ãƒ¼ ã‚¨ãƒ³ãƒˆãƒªã‚’è‡ªå‹•çš„ã«å®šç¾©ã™ã‚‹: 
# sectionPagesMenu: main

### Custom menu
### See https://stack.jimmycai.com/config/menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
# menu:
#   social:
#     - identifier: twitter
#       name: Twitter
#       url: https://x.com/katsu_ds_lab
#       params:
#         icon: brand-twitter
#     - identifier: github
#       name: GitHub
#       url: "https://github.com/katsu-ds-lab"
#       params:
#         icon: brand-github

languages:
  ja:
    # title: katsu DS Lab
    menu:
      social:
        - identifier: twitter
          name: Twitter
          url: https://x.com/katsu_ds_lab
          params:
            icon: brand-twitter
        - identifier: github
          name: GitHub
          url: "https://github.com/katsu-ds-lab"
          params:
            icon: brand-github
  # en:
  #   title: Katsu Data Science Lab
  #   menu:
  #     social:
  #       - identifier: twitter
  #         name: Twitter
  #         url: https://x.com/katsu_ds_lab
  #         params:
  #           icon: brand-twitter
  #       - identifier: github
  #         name: GitHub
  #         url: "https://github.com/katsu-ds-lab"
  #         params:
  #           icon: brand-github

# é–¢é€£ãƒšãƒ¼ã‚¸ (See also)
related:
    # é–¢é€£ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ãƒ»ãƒªã‚¹ãƒˆã«ç¾åœ¨ã®ãƒšãƒ¼ã‚¸ã‚ˆã‚Šã‚‚æ–°ã—ã„ãƒšãƒ¼ã‚¸ã‚’å«ã‚ã‚‹. 
    # ã“ã‚Œã«ã‚ˆã‚Š, æ–°ã—ã„é–¢é€£ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ãŒè¿½åŠ ã•ã‚Œã‚‹ã¨, å¤ã„æŠ•ç¨¿ã®å‡ºåŠ›ãŒå¤‰ã‚ã‚‹å¯èƒ½æ€§ãŒã‚ã‚‹: 
    includeNewer: true
    # 0ï½100. å€¤ãŒä½ã„ã»ã©ä¸€è‡´ã¯å¤šããªã‚‹ãŒ, é–¢é€£æ€§ã¯ä½ããªã‚‹å¯èƒ½æ€§ãŒã‚ã‚‹: 
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100
        - name: categories
          weight: 200

markup:
    tableOfContents:
        ordered: true
        # ordered: false
        endLevel: 4
        startLevel: 2
    
    goldmark:
        renderer:
            unsafe: true # HTMLã‚¿ã‚°ãŒãƒ¬ãƒ³ãƒ€ãƒªãƒ³ã‚°ã•ã‚Œã‚‹ã‚ˆã†ã«ã™ã‚‹
        extensions:
            # hardWraps: true
            passthrough:
                enable: true
                delimiters:
                    block:
                        - - \[
                          - \]
                        - - $$
                          - $$
                    inline:
                        - - \(
                          - \)
        parser:
          attribute:
            block: true
            title: true
          # ç‹¬ç«‹ã—ãŸç”»åƒè¦ç´ ã«å±æ€§ã‚’é©ç”¨ã™ã‚‹ã«ã¯ã€ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã®æŠ˜ã‚Šè¿”ã—å‹•ä½œã‚’ç„¡åŠ¹ã«ã™ã‚‹
          wrapStandAloneImageWithinParagraph: false
    
    highlight:
        codeFences: true
        # æŒ‡å®šè¡Œãƒã‚¤ãƒ©ã‚¤ãƒˆã® background-color ã‚’ 100% ã«ã™ã‚‹ãŸã‚, 
        # noClasses, lineNumbersInTable ã‚’ true, false ã¨ã™ã‚‹ã“ã¨!
        # ã‚¹ã‚¯ãƒ­ãƒ¼ãƒ«ã—ã¦ã‚‚ background-color ãŒé€”åˆ‡ã‚Œãªã„ã“ã¨ã‚’ç¢ºèªã™ã‚‹!

        # å¤–éƒ¨ CSS ãƒ•ã‚¡ã‚¤ãƒ«ã®ä»£ã‚ã‚Šã«ã‚¤ãƒ³ãƒ©ã‚¤ãƒ³ CSS ã‚¹ã‚¿ã‚¤ãƒ«ã‚’ä½¿ç”¨ã™ã‚‹ã‹ã©ã†ã‹ã€‚å¤–éƒ¨ CSS ãƒ•ã‚¡ã‚¤ãƒ«ã‚’ä½¿ç”¨ã™ã‚‹ã«ã¯ã€ã“ã®å€¤ã‚’ ã«è¨­å®šã—falseã€ ã‚³ãƒãƒ³ãƒ‰ã‚’ä½¿ç”¨ã—ã¦ CSS ãƒ•ã‚¡ã‚¤ãƒ«ã‚’ç”Ÿæˆã—ã¾ã™
        # hugo gen chromastyles
        # noClasses: true
        noClasses: false
        # lineNumbersInTable = false ã¨ã™ã‚‹ã¨è¡Œç•ªå·ã¾ã§ã‚³ãƒ”ãƒ¼ã•ã‚Œã‚‹.
        lineNumbersInTable: true
        guessSyntax: false
        lineNoStart: 1
        lineNos: false
        # wrapperClass: highlight
        # lineNos=inline
        # equivalent to lineNos=true and lineNumbersInTable=false
        # lineNos=table
        # equivalent to lineNos=true and lineNumbersInTable=true
        # # tabWidth: 4
        # lineAnchors: ""
        # hl_inline: false
        # <code>ã‚¿ã‚°å†…ã‚’å¼·èª¿è¡¨ç¤ºã™ã‚‹. codeã‚¿ã‚°ã¯ code-inline ã¨ã„ã†åå‰ã®ã‚¯ãƒ©ã‚¹ã‚’å–å¾—ã™ã‚‹: 
        # hl_Lines: ""
        # noHl: false
        # wrapperClass: highlight
        # style: monokai
